config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_a_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'user_all_office'
      get 'basic_information'
    end
    collection { post :csv_import }
    resources :attendances, only: :update
  end
  
end

app/models/user.rb
class User < ApplicationRecord

                      #ユーザーが削除されると関連する勤怠データも削除する(dependent:依存)
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 100},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30}, allow_blank: true #空白の時、バリデーションをスルーする
  validates :basic_time, presence: true
  validates :work_time, presence: true
  validates :affiliation, length: { in: 2..10}, allow_blank: true
  validates :employee_number, presence: true
  validates :uid, length: { in: 1..5}, allow_blank: true
  validates :basic_work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true

  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  
   # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true, skip_blanks: true) do |row|
      user = new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!
    end
  end
  
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time",
     "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:user_all_office, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:user_all_office, :show, :edit, :update, :index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index,:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: [:show, :user_all_office]

  def index
    @users = User.all
    if params[:name].present?
      @users = @users.get_by_name params[:name]
    end
    if params[:id].present?
      @user = User.find_by(id: @users.id)
    else
      @user = User.new
    end
    #@users = User.all
    #if params[:id].present?
      #@user = User.find(params[:id])
    #else
      #@user = User.new
    #end
  end
  
  def csv_import
    if params[:file].blank?
      flash[:danger] = "CSVファイルを選択して下さい。"
      redirect_to users_url(@user)
    else
      User.import(params[:file])
      flash[:success] = "CSVファイルをインポートしました"
      redirect_to users_url(@user)
    end
  end
  
  def show        #Date.current当日取得　biginning_of_monthはRailsのメソッド
    #@first_day = Date.current.beginning_of_month
    #@last_day = @first_day.end_of_month #end_of_monthは当月の終日を取得(30日,31日は判断してくれる)
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    if @user.update_attributes(basic_a_info_params)
      flash[:success] = "#{@user.name}の情報を更新しました。"
      redirect_to users_url(@user)
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def update_a_info
    if @user.update_attributes(basic_a_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def user_all_office
    @users = Attendance.all.includes(:user) 
  end
  
  def basic_information
  end 
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
    
    def basic_a_info_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid,
                     :password, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time,format: :time)
    format("%.2f",((time.hour * 60) + time.min) / 60.0)
  end
  

end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_user_a.html.erb
<%= form_with(model: user, url: user_url(user), local: true) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :名前, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :メールアドレス, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :所属, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :社員番号, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>

  <%= f.label :カードID, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label :パスワード, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :基本勤務時間, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>
  
  <%= f.label :指定勤務開始時間, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :指定勤務終了時間, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/basic_information.html.erb
<% provide(:title, 'Basic Information' ) %>

<h1>基本情報の修正（改修中）</h1>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, "user--edit") %>
<% provide(:button_text, "更新") %>

<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% provide(:class_text, 'user-show') %>
<% provide(:button_text, '編集する') %>

<h1>ユーザー一覧</h1>

<%= form_with(url: csv_import_users_path, local: true) do |f| %>
  <%= f.file_field :file, accept:'.csv', class: "field-info" %>
  <%= f.submit "CSVをインポート", class: "btn btn-primary btn-import" %>
<% end %>
<br>
<br>

<% @users.each do |user| %>
  <% unless user.admin? %>
    <%= user.name %>
  <% end %>
  <div>
    <% if current_user.admin? && !current_user?(user) %>
      <%= link_to "削除", user, method: :delete,data: { confirm: "#{user.name}を削除してよろしいですか？"},
          class: "btn btn-primary" %> <!-- dataから　アラート表示 -->
    <% end %>
  </div>
  <% unless user.admin? %>
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#list<%= user.id %>">編集</button>
          </h4>
        </div>
        <div id="list<%= user.id %>" class="panel-collapse collapse">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                <%= render partial: 'user_a', locals: { user: user } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>

<h1>ユーザー登録</h1>

<!--<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= <!--render 'form'--> %>
  </div>
</div>-->

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>　
        <%= l(@first_day, format: :middle) %>　時間管理表　
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
      </td>
      <td>
        <div>指定勤務開始時間　<%= l(@user.designated_work_start_time, format: :time) %></div>
        <div>指定勤務終了時間　<%= l(@user.designated_work_end_time, format: :time) %></div>
      </td>
      <td colspan="3"><br>基本時間　<%= @user.basic_time.hour %>時間</td> <!--https://techacademy.jp/magazine/7790-->
      <td><br>初日　<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr> <!--present?は値が入っていればtrue。?はつける。a ? b : c 三項演算子aが真であれば b さもなくば c-->
      <td>所属 　<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名　<%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.uid %></td>
      <td>出勤日数　<%= @worked_sum %>日</td>
      <td>末日　<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<h4>【所属長承認申請のお知らせ】  <% %></h4>
<h4>【勤怠変更申請のお知らせ】  <% %></h4>
<h4>【残業申請のお知らせ】  <% %></h4>
<br>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", "#", class: "btn btn-primary" %>
</div>
<div class="btn-users-show">
  <%= link_to "勤怠修正ログ（承認済）", "#", class: "btn btn-primary" %>
</div>

<div>
  <table class="table table-bordered table-condensed table-striped" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3"></th>
        <th></th>
        <th></th>
        <th colspan="7">【実績】</th>
        <th colspan="5">【所定外勤務】</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="2">退社</th>
        <th colspan="2">終了予定時間</th>
      </tr>
      <tr>
        <th>残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th>時</th>
        <th>分</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
    </thead>

    <tbody>
      <!--範囲オブジェクト(@first_day..@last_day),または配列[*@first_day..@last_day]  -->
      <% @attendances.each do |day| %>
        <tr>
          <td><%= link_to "残業申請", "#", class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user,day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= l(day.started_at, format: :time) if day.started_at.present? %></td>
          <td><%= l(day.finished_at, format: :time) if day.finished_at.present? %></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td></td>
        <td colspan="2">累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="2">累計在社時間</td>
        <td rowspan="2"></td>
      </tr>
      <tr>      <!--.to_fは文字列を浮動小数点　.to_iは文字列から整数   -->
        <td></td>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="2"><%= format("%.2f", @total_working_times.to_f).to_f %></td>
      </tr>
    </tfoot>    
  </table>
</div>

app/views/users/user_all_office.html.erb
<% provide(:title, 'User All Office' ) %>

<h1>出勤中社員一覧</h1>

<div>
  <table class="table table-bordered table-striped table-user-office" >
    <thead>
      <tr>
        <td>社員番号</td>
        <td>名前</td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |attendance| %>
        <tr>
          <% if attendance.started_at.present? && attendance.finished_at.blank? && (Date.current == attendance.worked_on) %>
            <td><%= attendance.user.employee_number %></td>
            <td><%= attendance.user.name %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>